#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendors/autoload.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\ClassLoader\UniversalClassLoader;

$loader = new UniversalClassLoader();
$loader->registerNamespaces(array(
    'Hoborg' => __DIR__ . '/../src',
));
$loader->register();


$input = new ArgvInput(); 
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'test');
$debug = !$input->hasParameterOption(array('--no-debug', ''));

require_once __DIR__ . '/Kernel.php';
$kernel = new Kernel($env, $debug);
$kernel->setHostDir(__DIR__);
$application = new Application($kernel);
$application->run();
